---
- yum:
    name: {{ fw_packages }}
    state: latest

    - name: open the port for the web server
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - 80
        - 443
...