---
- name: install the web and db servers
  yum:
    name:
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: latest

- name: start Database server
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    enabled: true
    state: started

- name: start web server
  service:
    name: "{{ ansible_local.custom.services.web_service }}"
    enabled: true
    state: started
...