---
# Playbook to install and enable the httpd service
- name: httpd playbook
  hosts: host1.test
  tasks:
    - name: install httpd
      yum:
        name: httpd
    - name: enable and start httpd
      service:
        name: httpd
        enabled: true
        state: started
    - name: webserver file
      copy:
        content: "Welcome to my web server\n"
        dest: /var/www/html/index.html
        force: false
        mode: 0444
    - name: FirewallD rules
      firewalld:
        permanent: true
        immediate: true
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
