---
# My first playbook
- name: simple playbook
  hosts: node.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: install vsftpd
      yum: name=vsftpd
    - name: enable and start vsftpd
      service: name=vsftpd enabled=true started=true
    - name: create readme file
      copy:
        content: "Welcome to my ftp server\n"
        dest: /var/ftp/pub/README
        force: no
        mode: 0444
...